### ISSUE TITLE
Print

### ISSUE THREAD

**Issue by novamix** [timcreative/light-bootstrap-dashboard-pro#8]
Hello, sorry for my English.
When you go to print something, a white space appears, as I can fix this?

![imprimir_fallo](https://cloud.githubusercontent.com/assets/4966653/14739636/2049a892-0889-11e6-8fd2-3d4bcc438339.png)

**Comment by alexandru-paduraru** [comment]
@novamix thank you for pointing out and sorry for the late response. For the printing option please go on assets/css/light-bootstrap-dashboard.css

1. to line 4158 and replace the **width:calc(100% - 260px)** with **max-width:calc(100% - 260px)**
2. at the end of your light-bootstrap-dashboard.css add this code:

    @media print{
       .sidebar{
           display: none;
       }
       .main-panel{
           width: 100%;
           max-width: none;
           max-height: none;
       }
       .wrapper{
           height: auto;
       }
    }

This will fix the issue. This fix will come by default in the next update.

Best,
Alex

**Comment by tarcisioangelo** [comment]
I have this problem in the pro version, how can I solve?

**Comment by tarcisioangelo** [comment]
solved with  min-width:calc(100% - 260px)

**Comment by tarcisioangelo** [comment]
I still can not solve with the min he breaks all

**Comment by alexandru-paduraru** [comment]
@tarcisioangelo thank you for using our product. Can you please tell us which version of the product you have? It should be fixed in the latest v1.3.0

**Comment by alexandru-paduraru** [comment]
We've made some further tests, please try this: 

```css
@media print{
    .sidebar{
        display: none !important;
    }
    .main-panel{
        width: 100% !important;
        min-width: 100% !important;
        max-width: none !important;
        max-height: none !important;
    }
    .wrapper{
        height: auto !important;
    }
}
```
